# Generated by Django 5.1.6 on 2025-03-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_rename_unit_name_unit_name'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('supply_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplyorder',
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderDetail',
            fields=[
                ('supply_order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('supply_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplyorder')),
            ],
            options={
                'db_table': 'supplyorderdetail',
            },
        ),
    ]
