# Generated by Django 5.1.6 on 2025-04-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='imageurl',
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product_id', 'imageurl')},
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='productimages',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
