# Generated by Django 5.1.6 on 2025-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_image_productimage_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='imageurl',
            field=models.CharField(db_column='imageurl', max_length=255),
        ),
    ]
