# Generated by Django 5.1.6 on 2025-03-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_name',
            new_name='name',
        ),
    ]
