# Generated by Django 5.1.6 on 2025-03-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer'),
        ('delivery', '0001_initial'),
        ('orders', '0002_alter_orders_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
