# Generated by Django 5.1.6 on 2025-03-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='loyalty_points',
            new_name='loyalty_point',
        ),
    ]
