# Generated by Django 5.1.6 on 2025-03-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_loyalty_points_customers_loyalty_point'),
        ('orders', '0002_alter_orders_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
