# Generated by Django 5.1.6 on 2025-04-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_point',
        ),
    ]
